#
# This is free software, lisence use MIT.....、.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# 2023年2月1日更新
name: Merge-upstream

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 */12 * * *'
  release:
      types: [published]


jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config --global user.email "KFER.Mercer@gmail.com"
          git config --global user.name "KFERMercer"

      - name: Disable fast-forward
        run: |
          git config pull.ff false

      - name: Fetch upstream
        run: |
          git fetch https://github.com/coolsnowwolf/lede.git

      - name: Merge upstream (always keep ours)
        run: |
          git merge FETCH_HEAD -s ours --no-edit

      - name: Push commits
        run: |
          git push origin master
